#--  FCC-ee  --
#
IncludeFile ObservablesHiggs_FCCee_240_SM_updated_lumi.conf
#
IncludeFile ObservablesHiggs_FCCee_365_updated_lumi.conf
#
#--  HLLHC  --
#
IncludeFile ObservablesHiggs_HLLHC_SM.conf
#
# Add observable for the Higgs width (ratio) in noMCMC mode
# ---------------------------------------------------------
Observable GammaHRatio   GammaHRatio   #Gamma_{Tot}/#Gamma_{Tot}^{SM} 1. -1.  noMCMC noweight
