######################################################################
# New theory nuisance parameters for FCCee Higgs production
# cross-sections
######################################################################
#
ModelParameter  theoerr_FCCee240        0.  0.0023295620053664676  0.
ModelParameter  theoerr_FCCee365        0.  0.0022585758048204183  0.
ModelParameter  NPmismatch_FCCee240        0.  0.006856788995512071  0.
ModelParameter  NPmismatch_FCCee365        0.  0.0034632124670086065  0.
#
