######################################################################
#--  Current aTGC uncertainties (central values set to SM)  --
#
IncludeFile aTGC_observables_Current_kappa_scaled_with_HEPfit_EWPOs_toyfit5.conf
#
IncludeFile aTGC_observables_HLLHC_Full_kappa_scaled_with_HEPfit_EWPOs_toyfit5.conf
#
#-- Future projections --
#
IncludeFile ObservablesVV_OO_FCCee_161_kappa_scaled_with_HEPfit_EWPOs_toyfit5.conf
IncludeFile ObservablesVV_OO_FCCee_240_kappa_scaled_with_HEPfit_EWPOs_toyfit5.conf
IncludeFile ObservablesVV_OO_FCCee_365_kappa_scaled_with_HEPfit_EWPOs_toyfit5.conf
#
