###################################################################### 
# Model name 
#--------------------------------------------------------------------- 
StandardModel
###################################################################### 
# Include here mandatory configuration files 
#--------------------------------------------------------------------- 
# 
IncludeFile ../../SMparameters.conf 
###################################################################### 
# Model Flags
#---------------------------------------------------------------------
ModelFlag  Mw  OMSII
#
ModelFlag  RhoZ  OMSII
#
ModelFlag  KappaZ  OMSII
#
#
# 
###################################################################### 
# Observables 
IncludeFile ../../ObservablesEW.conf 
#
#
# 
######################################################################
