###################################################################### 
# Model name 
#--------------------------------------------------------------------- 
StandardModel
###################################################################### 
# Include here mandatory configuration files 
#--------------------------------------------------------------------- 
# 
IncludeFile ../../SMparameters.conf 
###################################################################### 
# Model Flags
#---------------------------------------------------------------------
ModelFlag  NoApproximateGammaZ  true
#
#
# 
###################################################################### 
# Observables 
IncludeFile ../../ObservablesEW.conf 
#
#
# 
######################################################################
