#--  ILC  --
#
IncludeFile ObservablesHiggs_ILC_250_IDM_use_HEPfit_C1_values_decayrates_WFR_kala2_input_all.conf
#
IncludeFile ObservablesHiggs_ILC_350_IDM_use_HEPfit_C1_values_decayrates_WFR_kala2_input_all.conf
#
IncludeFile ObservablesHiggs_ILC_500_IDM_use_HEPfit_C1_values_decayrates_WFR_kala2_input_all.conf
#
# IncludeFile ObservablesHiggs_ILC_1000_SM.conf
#
#--  HLLHC  --
#
IncludeFile ObservablesHiggs_HLLHC_IDM_use_HEPfit_C1_values_decayrates_WFR_kala2_input_all.conf
#
# Add observable for the Higgs width (ratio) in noMCMC mode
# ---------------------------------------------------------
Observable GammaHRatio   GammaHRatio   #Gamma_{Tot}/#Gamma_{Tot}^{SM} 1. -1.  noMCMC noweight
