import uproot
import subprocess
from matplotlib import pyplot as plt
import matplotlib
import numpy as np
import os.path

from .parser import read_fit_results

plt.rcParams.update({
    #   "text.usetex": True,
    'text.latex.preamble': r'\usepackage{txfonts}'+'\n'+r'\usepackage{amsmath}',
    'savefig.dpi' : 300,
})


def print_to_file(message, file):
    """
    Function to print a message both to terminal output and to a file
    """
    print(message)
    print(message, file=file)


def group_plots(
    BPs,
    model_specs,
    working_dir,
    results_dirs,
    copy_obs=["deltalHHH_HLLHC_mod",],
):
    """
    Copy plots with the posterior distribution for observables from global fit results.
    The <model_specs> dictionary maps each collider configurations to a list of model 
    specifications. The latter must all have the same length, equal to the length of the
    {results_dirs} list. The function copies the relevant plots for each benchmark point
    and collider scenario, with the results for the i-th model specification
    <model_specs[scenario][i]> results being stored in the directory corresponding to the
    i-th entry in the {results_dirs} list.

    Parameters
    ----------
    BPs : list
        List of benchmark point names. Must correspond to the directory name for the BP
    model_specs : dict
        Dictionary mapping collider scenarios to model specifications.
    working_dir : str
        Working directory path, containing subdirectories for each benchmark point.
    results_dirs : list of str
        List of suffixes for the result directories. For each {results_dir} in this list,
        the corresponding results will be stored in the directory
        '{working_dir}/comparison_plots/results_{results_dir}/'
    copy_obs : list of str
        List of observables to copy. Default is ["deltalHHH_HLLHC_mod"].

    Returns
    -------
    None
    """

    # Create the output directories, if they do not yet exist
    for results_dir in results_dirs:
        subprocess.run(["mkdir", "-p", f"{working_dir}/comparison_plots/results_{results_dir}"])

    all_scenarios = model_specs.keys()

    for scenario in all_scenarios:
        for spec, results_dir in zip(model_specs[scenario] , results_dirs):
            for BP in BPs:
                for obs in copy_obs:
                    try:
                        input_path  = f"{working_dir}/{BP}/{scenario}/results_{spec}/Observables/{obs}.pdf"
                        output_path = f"{working_dir}/comparison_plots/results_{results_dir}/{obs}_{BP}_{scenario}.pdf"
                        subprocess.run(["cp", input_path, output_path])
                        print(F"Succesfully copied plot to {output_path}")
                    except:
                        print(f"file not found: {working_dir}/{BP}/{scenario}/results_{spec}/Observables/{obs}.pdf")


def print_klam_results(
    BPs,
    model_specs,
    working_dir,
    results_dirs,
):
    """
    Function to read the Statistics.txt file, generated by the global fit, and extract the 
    central value and uncertainty in the fitted kappa_lambda-1. The results are printed to
    the "{working_dir}/comparison_plots/results_{results_dir}/klam_results.txt" file, according
    to the "{BP},{kappa_lambda central value},{kappa_lambda error}" format.

    Parameters
    ----------
    BPs : list
        List of benchmark point names. Must correspond to the directory name for the BP
    model_specs : dict
        Dictionary mapping scenarios to a list of model specifications.
    working_dir : str
        Working directory path, containing subdirectories for each benchmark point.
    results_dirs : list of str
        List of suffixes for the result directories. For each {results_dir} in this list,
        the corresponding results will be stored in the directory
        '{working_dir}/comparison_plots/results_{results_dir}/'

    Returns
    -------
    None

    """

    scenarios = model_specs.keys()

    files = {}
    for BP in BPs:
        files[BP] = {}
        for scenario in scenarios:
            files[BP][scenario] = {}
            for model_spec in model_specs[scenario]:
                files[BP][scenario][model_spec] = f"{working_dir}/{BP}/{scenario}/results_{model_spec}/Observables/Statistics.txt"

    # Create the output directories, if they do not yet exist
    for results_dir in results_dirs:
        subprocess.run(["mkdir", "-p", f"{working_dir}/comparison_plots/results_{results_dir}"])


    print(f"\nReading klam fit results")
    kappa_lambda_results = read_fit_results(
        BPs=BPs,
        model_specs=model_specs,
        observables=["deltalHHH_HLLHC"],
        files=files,
    )

    for scenario in scenarios:
        for model_spec, results_dir in zip(model_specs[scenario], results_dirs):
            output_file = f"{working_dir}/comparison_plots/results_{results_dir}/klam_results_{scenario}.txt"
            with open(output_file, 'w') as f:
                print(f"Writing results to {output_file}")
                print(f"BP,klam,error", file=f)
                for BP in BPs:
                    if BP not in kappa_lambda_results or scenario not in kappa_lambda_results[BP] or model_spec not in kappa_lambda_results[BP][scenario]:
                        print(f"Skipping {BP}, {scenario}, {model_spec} as results are missing.")
                        continue

                    klam = kappa_lambda_results[BP][scenario][model_spec][0, 0] + 1
                    error = kappa_lambda_results[BP][scenario][model_spec][0, 1]
                    print(f"{BP},{klam},{error}", file=f)


def generate_klam_comparison_plot(
    BPs,
    model_specs,
    working_dir,
    results_dirs,
    BP_names,
    BP_lambdas,
    model,
    plot_labels=None,
    plot_titles=None,
    plot_true_klam=None,
    colors=None,
    show_plots=False,
    group_model_specs=False,
    figsize=(3.5, 4),
    fig_kwargs={},
    x_lim=None,
    y_lim_ax1=None,
    y_lim_ax2=None,
    leg_fontsize=9,
    spec_distance=0.1,
    upper_right_text=None,
    no_bottom_axis=False,
):
    r"""
    Compare the fit results for kappa_lambda between the benchmark points

    Parameters
    ----------
    BPs : list of str
        List of benchmark point names. Must correspond to the directory name for the BP
    model_specs : dict
        Dictionary mapping collider scenarios to a list of model specifications.
    working_dir : str
        Working directory path, containing subdirectories for each benchmark point.
    results_dirs : list or list of str
        List of suffixes for the result directories. For each {results_dir} in this list,
        the corresponding results will be stored in the directory
        '{working_dir}/comparison_plots/results_{results_dir}/'. Can also be a single string,
        in which case all plots are stored in the same directory.
    BP_names : list of str
        List with the names for the benchmark point, used in plots.
    BP_lambdas : list of float
        List of the corresponding BSM model prediction for kappa_lambda for each BP.
    model : str
        The BSM model considered. Currently can be either "IDM" or "Z2SSM"
    plot_labels : list of str
        List with the labels for each model benchmark point. Must have the same length as 
        the BP_names and BP_lambdas lists. If not set, labels will default to the 
        "{BP_name} $(\kappa_\lambda={klam})$" format, where "klam" is the corresponding
        prediction for kappa_lambda.
    plot_titles : dict, optional
        A dictionary in the form plot_titles[scenario][model_spec] containing the titles 
        for the plots. If not provided, no title is shown.
    plot_true_klam : dict, optional
        Whether to plot markers showing the UV model predictions for kappa_lambda and 
        respective kwargs. Must be a dictionary with arguments for pyplot.scatter(). 
        If not provided, no markers are shown.
    colors : list, optional
        List of colors assign to each model specification. If not set, the default 
        matplotlib color cycle will be used.
    show_plots : bool, optional
        Whether to show the plots or not. Default is False.
    group_model_specs : bool, optional
        Whether to generate a single plot per scenario, grouping all BPs and model specs 
        in the same plot. Default is False.
    figsize : tuple, optional
        Size for the generated plot. Default is (3.5, 4).
    fig_kwargs : dict, optional
        Additional keyword arguments for the figure.
    x_lim : tuple, optional
        Limits for the x-axis. If not set, the limits will be determined automatically.
    y_lim_ax1 : tuple, optional
        Limits for the y-axis of the upper subplot. If not set, the limits will be 
        determined automatically.
    y_lim_ax2 : tuple, optional
        Limits for the y-axis of the lower subplot. If not set, the limits will be 
        determined automatically.
    leg_fontsize : float, optional
        Font size for the legend. Default is 9.
    spec_distance : float, optional
        Horizontal distance between the markers for different model specifications, when
        grouping model specifications in the same plot. Default is 0.1.
    upper_right_text: str, optional
        Text to be shown in the upper right corner of the plot. Default is None.
    no_bottom_axis : bool, optional
        Whether to only show the top part of the plot, and not plot the difference in
        a bottom subplot. Default is False.

    Returns
    -------
    None

    """

    scenarios = list(model_specs.keys())
    
    if colors is None:
        # Default matplotlib color cycle
        colors = plt.rcParams['axes.prop_cycle'].by_key()['color']

    if plot_labels is None:
        plot_labels = [ rf"{BP_name} $(\kappa_\lambda={klam:.3g})$" for BP_name, klam in zip(BP_names, BP_lambdas) ]

    if model not in ["IDM", "Z2SSM"]:
        raise ValueError(f"Invalid model specified ({model}). Please choose either 'IDM' or 'Z2SSM'.")
    
    if isinstance(results_dirs, str):
        results_dirs = [results_dirs for model_spec in model_specs[scenarios[0]]]

    # Create the output directories, if they do not yet exist
    for results_dir in results_dirs:
        subprocess.run(["mkdir", "-p", f"{working_dir}/comparison_plots/results_{results_dir}"])

    files = {}
    for BP in BPs:
        files[BP] = {}
        for scenario in scenarios:
            files[BP][scenario] = {}
            for model_spec in model_specs[scenario]:
                files[BP][scenario][model_spec] = f"{working_dir}/{BP}/{scenario}/results_{model_spec}/Observables/Statistics.txt"

    print(f"\nReading klam fit results")
    kappa_lambda_results = read_fit_results(
        BPs=BPs,
        model_specs=model_specs,
        observables=["deltalHHH_HLLHC"],
        files=files,
    )

    spec_distance = spec_distance
    for scenario in scenarios:
        n_specs = len(model_specs[scenario])
        if group_model_specs:
            if not no_bottom_axis:
                fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True, figsize=figsize, height_ratios=[0.7, 0.3], gridspec_kw=dict(hspace=0.), **fig_kwargs)
            else:
                fig, ax1 = plt.subplots(1, 1, figsize=figsize, **fig_kwargs)

        for spec_idx, (model_spec, results_dir) in enumerate(zip(model_specs[scenario], results_dirs)):
            x = BP_lambdas
            if not group_model_specs:
                if not no_bottom_axis:
                    fig, (ax1, ax2) = plt.subplots(2, 1, sharex=True, figsize=figsize, height_ratios=[0.7, 0.3], gridspec_kw=dict(hspace=0.), **fig_kwargs)
                else:
                    fig, ax1 = plt.subplots(1, 1, figsize=figsize, **fig_kwargs)
            elif n_specs != 1:
                x = np.array(BP_lambdas) + spec_distance * (-0.5*(n_specs-1) + spec_idx)/(n_specs-1)

            means  = {BP : kappa_lambda_results[BP][scenario][model_spec][0, 0] + 1 for BP in BPs}
            errors = {BP : kappa_lambda_results[BP][scenario][model_spec][0, 1]     for BP in BPs}
            for i, BP in enumerate(BPs):

                if group_model_specs:
                    idx = spec_idx
                    if i == 0:
                        label = plot_labels[idx]
                    else:
                        label = None
                else:
                    idx = i
                    label = plot_labels[idx]

                ax1.errorbar(x=x[i],
                            y=means[BP],
                            yerr=(errors[BP],), 
                            fmt='o', 
                            linewidth=1.5, 
                            capsize=3.5, 
                            markersize=4, 
                            label=label,
                            color=colors[idx])

                if not no_bottom_axis:
                    ax2.errorbar(x=x[i],
                                y=means[BP] - BP_lambdas[i],
                                yerr=(errors[BP],), 
                                fmt='o', 
                                linewidth=1.5, 
                                capsize=3.5, 
                                markersize=4, 
                                color=colors[idx])
                
                    ax2.axhline(y=0, c='0.6', linewidth=1)

            if plot_true_klam is not None:
                if "s" not in plot_true_klam:     plot_true_klam["s"] = 25
                if "marker" not in plot_true_klam:  plot_true_klam["marker"] = 'x'
                if "color" not in plot_true_klam:   plot_true_klam["color"] = 'black'
                if "label" not in plot_true_klam:   plot_true_klam["label"] = rf'{model} prediction'
                ax1.scatter(BP_lambdas, BP_lambdas, **plot_true_klam)

            # ax2.tick_params(axis='x', size=10, labelsize=12)
            # ax2.tick_params(axis='x', which='minor', size=6)

            # ax1.set_yticks(BP_lambdas)
            # ax2.set_xticks(BP_lambdas)
            # ax2.set_xticklabels(BP_lambdas,fontsize=16)
            if x_lim is not None:
                ax1.set_xlim(x_lim)
            if y_lim_ax1 is not None:
                ax1.set_ylim(y_lim_ax1)

            ax1.set_ylabel(r'$\kappa_{\lambda}^\text{fit}$', fontsize=15)
            ax1.grid(which='both', linestyle='--', linewidth=0.5)
            ax1.legend(loc='best', fontsize=leg_fontsize)

            if not no_bottom_axis:
                if y_lim_ax2 is not None:
                    ax2.set_ylim(y_lim_ax2)
                ax2.set_ylabel(r'$\kappa_{\lambda}^\text{fit} - \kappa_{\lambda}^\text{true}$', fontsize=15)
                ax2.set_xlabel(rf'$\kappa_{{\lambda}}^\text{{true}}$ ({model} predictions)', fontsize=13)
                ax2.grid(which='both', linestyle='--', linewidth=0.5)
            else:
                ax1.set_xlabel(rf'$\kappa_{{\lambda}}^\text{{true}}$ ({model} predictions)', fontsize=13)

                

            if not upper_right_text is None:
                ax1.text(
                    1,
                    1,
                    upper_right_text,
                    horizontalalignment="right",
                    verticalalignment="bottom",
                    transform=ax1.transAxes,
                    fontsize=8,
                )

            if plot_titles is not None and scenario in plot_titles and model_spec in plot_titles[scenario]:
                ax1.set_title(plot_titles[scenario][model_spec], fontsize=10)
            fig.tight_layout()   # Makes sure labels are not cut off

            if not no_bottom_axis:
                fig.savefig(working_dir + f'/comparison_plots/results_{results_dir}/kappa_lambda_results_{scenario}.pdf')
            else:
                fig.savefig(working_dir + f'/comparison_plots/results_{results_dir}/kappa_lambda_results_{scenario}_no_bottom_axis.pdf')

    if show_plots:
        plt.show()


def compare_BP_results_uproot(
    BPs,
    model_specs,
    working_dir,
    results_dir,
    spec_labels,
    BP_names,
    BP_lambdas,
    model,
    scenario_titles=None,
    plot_titles=None,
    colors=None,
    show_plots=False,
    legend_fontsize=8.,
):
    """
    Compare the posterior kappa_lambda distribution between different model specifications.
    The distributions are read from the MCout.root files with the uproot package. The function 
    generates comparison plots between the model_specs, as well as a summary latex table.

    Parameters
    ----------
    BPs : list of str
        List of benchmark point names. Must correspond to the directory name for the BP
    model_specs : dict
        Dictionary mapping collider scenarios to a list of model specifications.
    working_dir : str
        Working directory path, containing subdirectories for each benchmark point.
    results_dir : str
        Suffix of the name of the directory to store the results. Results are stored in
        '{working_dir}/comparison_plots/results_{results_dir}/'.
    spec_labels : list of str
        List with the labels for each model specification. Must have the same length as the
        model_specs[scenario] lists, for each collider scenario.
    BP_names : list of str
        List with the names for the benchmark point, used in plots.
    BP_lambda : list of float
        List of the corresponding BSM model prediction for kappa_lambda for each BP.
    model : str
        The BSM model considered. Currently can be either "IDM" or "Z2SSM"
    scenario_titles : list, optional
        A list containing the titles for the scenarios. If not provided, default titles 
        will be used.
    plot_titles : dict, optional
        A dictionary in the form plot_titles[BP][scenario] containing the titles for 
        the plots. If not provided, the format "<model> <BP_name>, <scenario_title>"
        will be used.
    colors : list, optional
        List of colors assign to each model specification. If not set, the default 
        matplotlib color cycle will be used.
    show_plots : bool, optional
        Whether to show the plots or not. Default is False.
    legend_fontsize : float, optional
        Font size for the legend. Default is 8.

    Returns
    -------
    None

    """

    scenarios = model_specs.keys()

    # Deal with optional arguments
    if colors is None:
        # Default matplotlib color cycle
        colors = plt.rcParams['axes.prop_cycle'].by_key()['color']

    colors_rgb_list = [ matplotlib.colors.to_rgb(c) for c in colors ]

    if model not in ["IDM", "Z2SSM"]:
        raise ValueError(f"Invalid model specified ({model}). Please choose either 'IDM' or 'Z2SSM'.")
    
    if scenario_titles is None:
        for scenario in scenarios:
            if scenario == f"{model}_FCCee240":
                scenario_titles = [rf"FCC-ee$_{{240}}$"]
            elif scenario == f"{model}_FCCee240_FCCee365":
                scenario_titles = [rf"FCC-ee$_{{240}}$ + FCC-ee$_{{365}}$"]
            elif scenario == f"{model}_FCCee240_FCCee365_HLLHClambda":
                scenario_titles = [rf"FCC-ee$_{{240}}$ + FCC-ee$_{{365}}$ + $\kappa_{{\lambda}}$ at HL-LHC"]

    if plot_titles is None:
        plot_titles = {BP: {scenario: rf"{model} {BP_name}, {scenario_title}" for scenario_title in scenario_titles} for BP, BP_name in zip(BPs, BP_names)}


    # Create the output directory, if it does not yet exist
    subprocess.run(["mkdir", "-p", f"{working_dir}/comparison_plots/results_{results_dir}"])

    fig_num = 0
    for scenario in scenarios:
        for BP, BP_name, BP_lambda in zip(BPs, BP_names, BP_lambdas):

            # BP_lambda = BP_lambdas[BP]
            fig = plt.figure(fig_num, figsize=(4.0, 3.5))
            fig_num += 1
            ax = plt.gca()
            ax.set_title(plot_titles[BP][scenario])
            ax.set_xlabel(r"$\kappa_{\lambda}$", fontsize=14)
            ax.set_ylabel("Posterior distribution", fontsize=12)

            for spec, label, color_rgb in zip(model_specs[scenario], spec_labels, colors_rgb_list):

                # Open the ROOT file
                if BP == "BP_lambda1" and spec == "fits_realistic_HL_LHC_WFR_kala2_input_all_all_EW_mods_small_priors_long":
                    file_path = f"{working_dir}/{BP}/{scenario}/results_{spec[:-5]}_strict/MCout.root"
                else:
                    file_path = f"{working_dir}/{BP}/{scenario}/results_{spec}/MCout.root"
                with uproot.open(file_path) as file:

                    hist_lmbd_y, hist_lmbd_x = file["deltalHHH_HLLHC"].to_numpy()
                    hist_lmbd_x = hist_lmbd_x + 1 
                    plt.hist(hist_lmbd_x[:-1], hist_lmbd_x, weights=hist_lmbd_y, label=label, density=True, histtype="step", edgecolor=(*color_rgb, 1.0), facecolor=(*color_rgb, 0.5), linewidth=1.5, fill=True)

            scale = 1.2
            ylow, yhigh = ax.get_ylim()
            ax.set_ylim(ylow, yhigh + (scale-1)*(yhigh-ylow))

            plt.axvline(BP_lambda, color="black", linestyle="--", label=rf"{model} {BP_name} value"+"\n"+rf"($\kappa_{{\lambda}}$ = {BP_lambda:.2f})")
            plt.legend(fontsize=legend_fontsize, loc="best")
            plt.tight_layout()
            plt.savefig(f"{working_dir}/comparison_plots/results_{results_dir}/{model}_{BP}_{scenario}_final.pdf")

    if show_plots:
        plt.show()


def generate_klam_latex_table(
    BPs,
    model_specs,
    working_dir,
    results_dir,
    spec_labels,
    BP_names,
    BP_lambdas,
):
    """
    Generates a LaTeX table, comparing the posterior kappa_lambda distribution between 
    different model specifications, as well as with the true value of the BP.

    Parameters
    ----------
    BPs : list of str
        List of benchmark point names. Must correspond to the directory name for the BP
    model_specs : dict
        Dictionary mapping collider scenarios to a list of model specifications.
    working_dir : str
        Working directory path, containing subdirectories for each benchmark point.
    results_dir : str
        Suffix of the name of the directory to store the results. Results are stored in
        '{working_dir}/comparison_plots/results_{results_dir}/'.
    spec_labels : list of str
        List with the labels for each model specification. Must have the same length as the
        model_specs[scenario] lists, for each collider scenario.
    BP_names : list of str
        List with the names for the benchmark point, used in plots.
    BP_lambda : list of float
        List of the corresponding BSM model prediction for kappa_lambda for each BP.

    Returns
    -------
    None

    """

    scenarios = list(model_specs.keys())
    
    files = {}
    for BP in BPs:
        files[BP] = {}
        for scenario in scenarios:
            files[BP][scenario] = {}
            for model_spec in model_specs[scenario]:
                files[BP][scenario][model_spec] = f"{working_dir}/{BP}/{scenario}/results_{model_spec}/Observables/Statistics.txt"

    print(f"\nReading klam fit results")
    kappa_lambda_results = read_fit_results(
        BPs=BPs,
        model_specs=model_specs,
        observables=["deltalHHH_HLLHC"],
        files=files,
    )

    table_tex_output_file = working_dir + f'/comparison_plots/results_{results_dir}/klam_results_table.tex'
    headers = ["", "True value",] + spec_labels
    columns = BP_names
    # table_text = "\\hline\n" + " & ".join(headers) + "\\\\\n"
    table_text = " & ".join(headers) + "\\\\\n"
    table_text += "\\hline"
    for idx, (column, BP, BP_lambda) in enumerate(zip(columns, BPs, BP_lambdas)):
        table_text += "\\hline\n"
        table_text += f"{column} & {BP_lambda:.3g}"
        for model_spec in model_specs[scenario]:
            klam = kappa_lambda_results[BP][scenario][model_spec][0,0] + 1
            klam_err_abs = kappa_lambda_results[BP][scenario][model_spec][0,1]
            klam_err_rel = klam_err_abs / klam
            table_text += rf" & ${klam:.2f}\pm{klam_err_abs:.2f}\;[\textcolor{{violet}}{{{100*klam_err_rel:.2g}\%}}]$"
        table_text += "\\\\"

    with open(table_tex_output_file, "w") as out_file:
        print_to_file("\\begin{tabular}{c||c|c|c}", file=out_file)
        print_to_file(table_text, file=out_file)
        print_to_file("\\end{tabular}", file=out_file)
        # print("\\hline\n\\end{tabular}", file=out_file)

    print(f"Saved summary latex table onto file {table_tex_output_file}")
