######################################################################
# New theory nuisance parameters for FCCee Higgs production
# cross-sections
######################################################################
#
ModelParameter  theoerr_FCCee240        0.  0.00147798320333868338  0.
ModelParameter  theoerr_FCCee365        0.  0.00133433631331031123  0.
ModelParameter  NPmismatch_FCCee240        0.  0.00000000000000000000  0.
ModelParameter  NPmismatch_FCCee365        0.  0.00000000000000000000  0.
#
